### ISSUE TITLE
RFE - make logging an option

### ISSUE THREAD

**Issue by juggledad** [O-Hahn/node-red-contrib-speakerpi#2]
It would be nice to make the logging optional, say an option to turn on logging. This would reduce the volume of messages on the log and if you are using more than one instance of the node, you could turn logging on per instance to help with debugging (if you needed to)

Thanks for the node, I'm using it for a halloween skeleton to talk to my grandsons (5, 4, 3 and 2)

**Comment by O-Hahn** [comment]
Of course - i have now removed the debug logs from the code.
