### ISSUE TITLE
README nit - code should be on two lines

### ISSUE THREAD

**Issue by juggledad** [O-Hahn/node-red-contrib-speakerpi#3]
The following causes an error if a copy/paste is done so this:should be on two lines

> Additionally you have to install on the Raspberry Pi
> sudo apt-get update sudo apt-get install libasound2-dev
should be this

> Additionally you have to install on the Raspberry Pi
> sudo apt-get update 
> sudo apt-get install libasound2-dev

**Comment by O-Hahn** [comment]
will fix the documentation - thx
