### ISSUE TITLE
Can't compile with Node 6.9.x because of serial port

### ISSUE THREAD

**Issue by rmey** [O-Hahn/node-red-contrib-speakerpi#5]
Installation on Node 6.9.2 and npm 3.10.9 fails because of old Serial Port Dependency.
pi@demopi:~/.node-red $ npm install node-red-contrib-speakerpi

> serialport@2.0.6 install /home/pi/.node-red/node_modules/serialport
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/pi/.node-red/node_modules/serialport/build'
  CXX(target) Release/obj.target/serialport/src/serialport.o
In file included from ../../nan/nan.h:182:0,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
../../nan/nan_maybe_43_inl.h: In function 'Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)':
../../nan/nan_maybe_43_inl.h:221:58: warning: 'v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:3031): Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:188,
                 from ../src/serialport.h:5,
                 from ../src/serialport.cpp:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)':
../../nan/nan_implementation_12_inl.h:40:38: warning: 'static v8::Local<v8::Value> v8::BooleanObject::New(bool)' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:4007): Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from ../src/serialport.h:5:0,
                 from ../src/serialport.cpp:3:
../../nan/nan.h: At global scope:
../../nan/nan.h:590:20: error: variable or field 'AddGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field 'RemoveGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field 'AddGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field 'RemoveGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h: In function 'bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
../../nan/nan.h:1933:16: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:2750): Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:115:116: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->baudRate = Nan::Get(options, Nan::New<v8::String>("baudRate").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                    ^
../src/serialport.cpp:116:116: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->dataBits = Nan::Get(options, Nan::New<v8::String>("dataBits").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                    ^
../src/serialport.cpp:117:120: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->bufferSize = Nan::Get(options, Nan::New<v8::String>("bufferSize").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                        ^
../src/serialport.cpp:119:131: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   baton->stopBits = ToStopBitEnum(Nan::Get(options, Nan::New<v8::String>("stopBits").ToLocalChecked()).ToLocalChecked()->ToNumber()->NumberValue());
                                                                                                                                   ^
../src/serialport.cpp: In function 'void EIO_AfterOpen(uv_work_t*)':
../src/serialport.cpp:159:31: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
     int fd = argv[1]->ToInt32()->Int32Value();
                               ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:180:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
../src/serialport.cpp:199:116: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->baudRate = Nan::Get(options, Nan::New<v8::String>("baudRate").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                    ^
../src/serialport.cpp:200:116: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->dataBits = Nan::Get(options, Nan::New<v8::String>("dataBits").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                    ^
../src/serialport.cpp:201:120: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   baton->bufferSize = Nan::Get(options, Nan::New<v8::String>("bufferSize").ToLocalChecked()).ToLocalChecked()->ToInt32()->Int32Value();
                                                                                                                        ^
../src/serialport.cpp:203:131: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8166): Use maybe version [-Wdeprecated-declarations]
   baton->stopBits = ToStopBitEnum(Nan::Get(options, Nan::New<v8::String>("stopBits").ToLocalChecked()).ToLocalChecked()->ToNumber()->NumberValue());
                                                                                                                                   ^
../src/serialport.cpp: In function 'void EIO_AfterUpdate(uv_work_t*)':
../src/serialport.cpp:242:31: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
     int fd = argv[1]->ToInt32()->Int32Value();
                               ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Write(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:263:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:374:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:493:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:542:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)':
../src/serialport.cpp:603:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated (declared at /home/pi/.node-gyp/6.9.2/include/node/v8.h:8202): Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->ToInt32()->Int32Value();
                             ^
serialport.target.mk:94: recipe for target 'Release/obj.target/serialport/src/serialport.o' failed
make: *** [Release/obj.target/serialport/src/serialport.o] Error 1
make: Leaving directory '/home/pi/.node-red/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm"
gyp ERR! cwd /home/pi/.node-red/node_modules/serialport
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/.node-red/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.38-v7+
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/pi/.node-red/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/.node-red/node_modules/serialport
node-pre-gyp ERR! node -v v6.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/.node-red/node_modules/serialport/build/Release/node-v48-linux-arm' (1)

**Comment by rmey** [comment]
Is the serial port dependency needed?

**Comment by O-Hahn** [comment]
yes - because in the buffer mode it streams directly. There is a newer version of the serialport npm package. i have to check if the usage is the same.. you can try adopting the package.json with the latest version and install again..

**Comment by O-Hahn** [comment]
put a new version of this package - it should resolve the problem
