### ISSUE TITLE
WAV stream not working but same file saved and file input works

### ISSUE THREAD

**Issue by alan-rpi** [O-Hahn/node-red-contrib-speakerpi#6]
Hi, many thanks for making this node available.

I'm running on a Rasp Pi 3 Jessie and sending text to Watson Speech to Text node. It returns a WAV stream as msg.speech. 

If I stream that into Speakerpi then nothing is heard. On the other hand, if I save the file as a WAV file and then feed the file name (Given file) into Speakerpi then I hear the speech. This method gives a playback lag so I would like to get the stream function working. 

I've tried the different combinations of bit depth and sample rate though I notice that Windows says the WAV file is 352kbps, but as I said Speakerpi plays the saved file OK. On the debug I noticed that msg.speech is split into 100s of segments.

Any ideas or anything I can do to give more info? Many thanks.

Alan
![speech](https://cloud.githubusercontent.com/assets/25422008/26028276/292513a4-3815-11e7-86be-4f892f62c208.jpg)

PS I installed node-red-contrib-speaker and that played the speech OK but aborted Node-Red at the end. The documentation for that node states that Watson delivers 2 audio channels, 16-bit sampling resolution at 11,025 Hz sampling rate which are the default values in that node. Your node does not have 11,025 Hz. Is that the problem? If so, could it be added? But why does the same saved file work?

**Comment by O-Hahn** [comment]
i have added the 11025hz version into the parameters options - please test again. I have to setup a new raspy to test this node again..

**Comment by alan-rpi** [comment]
Thanks. I've just installed 0.0.38 but streaming still doesn't work even at 11025hz. As before, if the same stream is saved to a file then it does play OK using the filename, but this is slower.

This time I used a short message so I able to debug it:
====================
21/05/2017, 15:44:28node: c237f866.59a738Hello : msg : Object
>object  _msgid: "23359079.dcca7"
topic: "Hello"
payload: "a a Testing Testing Testing"
> speech: buffer[89322]raw
     >[0 … 9]
       0: undefined
       1: undefined
      etc etc
    > [89320 … 89321]
       89320: undefined
       89321: undefined
====================
Why these are undefined I don't know as the same data (msg.speech) is copied to msg.payload using the  Change node and then saved with the File node and then after a 1 second delay played OK with your Speakerpi node.

**Comment by janvda** [comment]
I am having the same issue.  So file based it also works for me, but stream based I can also not get it working.

**Comment by 0x69676f72** [comment]
File based doesn't work for Anker bluetooth. Browser youtube words.

**Comment by O-Hahn** [comment]
should now be solved with the new version...

**Comment by shinjihun1** [comment]
Same issue to me.
And, the results using "aplay -t raw -c 1 -f S16_LE -r 16000 xxx.wav" was not working also.
Thanks.

**Comment by shinjihun1** [comment]
20 Sep 10:20:28 - [error] [speakerpi-output:cf9caebb.99c14] SpeakerPI: No msg.speech object found
20 Sep 10:20:28 - [error] [speakerpi-output:cf9caebb.99c14] SpeakerPI: No msg.speech object found
