### ISSUE TITLE
speakerpi throws an error and I can't find any solution online

### ISSUE THREAD

**Issue by kyteinsky** [O-Hahn/node-red-contrib-speakerpi#9]
I am using Raspberry Pi 4B 1GB RAM

- Node-RED version: v1.1.0
- Node.js  version: v12.18.2
- Linux 5.4.47-v7l+ arm LE

I tried to play wav file, mp3 file and also raw audio buffer using Node RED but of no use, there is no sound.

I have tested the speakers and audio file using OMXplayer, that works, but speakerpi doesn't.

## Here is the error -----------------------------------
Error: Package subpath './v4' is not defined by "exports" in /home/pi/.node-red/node_modules/uuid/package.json

## This is my simple flow ----------------------------------
[{"id":"c0bf711f.1c725","type":"speakerpi-output","z":"1b409f87.00788","choose":"givenfile","filename":"/home/pi/music.wav","channels":"1","bitdepth":"16","samplerate":"22050","name":"","x":1610,"y":300,"wires":[[]]},{"id":"fcf87097.2f62","type":"inject","z":"1b409f87.00788","name":"","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1330,"y":300,"wires":[["c0bf711f.1c725"]]}]

## Please help me out

**Comment by O-Hahn** [comment]
i try to fix the problem today - it is because of the new uuid package ..

**Comment by kyteinsky** [comment]
@O-Hahn 
Thanks sir
Very good work. Keep it up.


I made it work with old Node js (10) installation with the new node red, edited the install script of node red not to uninstall the previous version. It works like charm. Thanks for the node.

**Comment by O-Hahn** [comment]
i have found how to solve with the new version ... - i am setting up my raspi to the most current verision - so that i can test the uuid problem. think that today i will have the fix.

**Comment by O-Hahn** [comment]
should be solved
